"""add process and user_process mapping

Revision ID: 142349cbdee9
Revises: da2ddcd5aa2d
Create Date: 2026-02-25 13:11:57.621456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142349cbdee9'
down_revision: Union[str, Sequence[str], None] = 'da2ddcd5aa2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mes_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mes_process')),
    sa.UniqueConstraint('name', name=op.f('uq_mes_process_name'))
    )
    op.create_index(op.f('ix_mes_process_code'), 'mes_process', ['code'], unique=True)
    op.create_index(op.f('ix_mes_process_id'), 'mes_process', ['id'], unique=False)
    op.create_table('sys_user_process',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['mes_process.id'], name=op.f('fk_sys_user_process_process_id_mes_process'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_user_process_user_id_sys_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'process_id', name=op.f('pk_sys_user_process'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_process')
    op.drop_index(op.f('ix_mes_process_id'), table_name='mes_process')
    op.drop_index(op.f('ix_mes_process_code'), table_name='mes_process')
    op.drop_table('mes_process')
    # ### end Alembic commands ###
