"""add product lifecycle, revisions and order product version snapshot

Revision ID: c9d8e7f6a5b4
Revises: a9e6c1f4d2b7
Create Date: 2026-03-07 16:00:00.000000

"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d8e7f6a5b4"
down_revision: Union[str, Sequence[str], None] = "a9e6c1f4d2b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _build_product_snapshot(conn, *, product_id: int, product_name: str) -> str:
    parameter_rows = conn.execute(
        sa.text(
            """
            SELECT
                param_key,
                param_category,
                param_type,
                param_value,
                sort_order,
                is_preset
            FROM mes_product_parameter
            WHERE product_id = :product_id
            ORDER BY sort_order ASC, id ASC
            """
        ),
        {"product_id": product_id},
    ).mappings()

    parameters = [
        {
            "name": str(row["param_key"]),
            "category": str(row["param_category"] or ""),
            "type": str(row["param_type"] or "Text"),
            "value": str(row["param_value"] or ""),
            "sort_order": int(row["sort_order"] or 0),
            "is_preset": bool(row["is_preset"]),
        }
        for row in parameter_rows
    ]
    snapshot = {
        "name": product_name,
        "parameters": parameters,
    }
    return json.dumps(snapshot, ensure_ascii=False, separators=(",", ":"))


def _seed_initial_product_revisions() -> None:
    conn = op.get_bind()
    now = datetime.now(UTC).replace(tzinfo=None)
    product_rows = conn.execute(
        sa.text(
            """
            SELECT id, name, lifecycle_status, created_at, updated_at
            FROM mes_product
            ORDER BY id ASC
            """
        )
    ).mappings()

    for row in product_rows:
        product_id = int(row["id"])
        snapshot_json = _build_product_snapshot(
            conn,
            product_id=product_id,
            product_name=str(row["name"]),
        )
        timestamp = row["updated_at"] or row["created_at"] or now
        conn.execute(
            sa.text(
                """
                INSERT INTO mes_product_revision
                    (
                        product_id,
                        version,
                        lifecycle_status,
                        action,
                        note,
                        source_revision_id,
                        snapshot_json,
                        created_by_user_id,
                        created_at,
                        updated_at
                    )
                VALUES
                    (
                        :product_id,
                        1,
                        :lifecycle_status,
                        'init',
                        'Initial snapshot generated by migration',
                        NULL,
                        :snapshot_json,
                        NULL,
                        :created_at,
                        :updated_at
                    )
                """
            ),
            {
                "product_id": product_id,
                "lifecycle_status": str(row["lifecycle_status"] or "effective"),
                "snapshot_json": snapshot_json,
                "created_at": timestamp,
                "updated_at": timestamp,
            },
        )


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "mes_product",
        sa.Column(
            "lifecycle_status",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("'draft'"),
        ),
    )
    op.add_column(
        "mes_product",
        sa.Column(
            "current_version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
    )
    op.add_column(
        "mes_product",
        sa.Column(
            "effective_version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "mes_product",
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "mes_product",
        sa.Column("inactive_reason", sa.Text(), nullable=True),
    )
    op.create_index(
        op.f("ix_mes_product_lifecycle_status"),
        "mes_product",
        ["lifecycle_status"],
        unique=False,
    )

    op.create_table(
        "mes_product_revision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.Column("source_revision_id", sa.Integer(), nullable=True),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["mes_product.id"],
            name=op.f("fk_mes_product_revision_product_id_mes_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_id"],
            ["mes_product_revision.id"],
            name=op.f("fk_mes_product_revision_source_revision_id_mes_product_revision"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["sys_user.id"],
            name=op.f("fk_mes_product_revision_created_by_user_id_sys_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mes_product_revision")),
        sa.UniqueConstraint(
            "product_id",
            "version",
            name="uq_mes_product_revision_product_id_version",
        ),
    )
    op.create_index(op.f("ix_mes_product_revision_id"), "mes_product_revision", ["id"], unique=False)
    op.create_index(
        op.f("ix_mes_product_revision_product_id"),
        "mes_product_revision",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mes_product_revision_source_revision_id"),
        "mes_product_revision",
        ["source_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mes_product_revision_created_by_user_id"),
        "mes_product_revision",
        ["created_by_user_id"],
        unique=False,
    )

    op.add_column("mes_order", sa.Column("product_version", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_mes_order_product_version"),
        "mes_order",
        ["product_version"],
        unique=False,
    )

    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            UPDATE mes_product
            SET lifecycle_status = 'effective',
                current_version = 1,
                effective_version = 1,
                effective_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP)
            """
        )
    )
    _seed_initial_product_revisions()
    conn.execute(
        sa.text(
            """
            UPDATE mes_order
            SET product_version = (
                SELECT effective_version
                FROM mes_product
                WHERE mes_product.id = mes_order.product_id
            )
            WHERE product_version IS NULL
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_mes_order_product_version"), table_name="mes_order")
    op.drop_column("mes_order", "product_version")

    op.drop_index(op.f("ix_mes_product_revision_created_by_user_id"), table_name="mes_product_revision")
    op.drop_index(op.f("ix_mes_product_revision_source_revision_id"), table_name="mes_product_revision")
    op.drop_index(op.f("ix_mes_product_revision_product_id"), table_name="mes_product_revision")
    op.drop_index(op.f("ix_mes_product_revision_id"), table_name="mes_product_revision")
    op.drop_table("mes_product_revision")

    op.drop_index(op.f("ix_mes_product_lifecycle_status"), table_name="mes_product")
    op.drop_column("mes_product", "inactive_reason")
    op.drop_column("mes_product", "effective_at")
    op.drop_column("mes_product", "effective_version")
    op.drop_column("mes_product", "current_version")
    op.drop_column("mes_product", "lifecycle_status")

