from __future__ import annotations

from dataclasses import dataclass

from app.core.rbac import ROLE_SYSTEM_ADMIN


@dataclass(frozen=True, slots=True)
class ModuleDefinition:
    module_code: str
    module_name: str


@dataclass(frozen=True, slots=True)
class FeatureDefinition:
    permission_code: str
    permission_name: str
    module_code: str
    page_code: str
    action_permission_codes: tuple[str, ...]
    dependency_permission_codes: tuple[str, ...] = ()
    hidden_in_capability_pack: bool = False
    assignable_role_codes: tuple[str, ...] = ()


def module_permission_code(module_code: str) -> str:
    return f"module.{module_code}.access"


MODULE_DEFINITIONS: tuple[ModuleDefinition, ...] = (
    ModuleDefinition(module_code="system", module_name="系统管理"),
    ModuleDefinition(module_code="user", module_name="用户管理"),
    ModuleDefinition(module_code="product", module_name="产品管理"),
    ModuleDefinition(module_code="equipment", module_name="设备管理"),
    ModuleDefinition(module_code="craft", module_name="工艺管理"),
    ModuleDefinition(module_code="quality", module_name="质量管理"),
    ModuleDefinition(module_code="production", module_name="生产管理"),
    ModuleDefinition(module_code="message", module_name="消息中心"),
)


MODULE_NAME_BY_CODE = {
    item.module_code: item.module_name for item in MODULE_DEFINITIONS
}


FEATURE_DEFINITIONS: tuple[FeatureDefinition, ...] = (
    FeatureDefinition(
        permission_code="feature.system.permission_catalog.view",
        permission_name="查看权限目录",
        module_code="system",
        page_code="function_permission_config",
        action_permission_codes=(
            "authz.permissions.catalog.view",
            "authz.permissions.me.view",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.system.role_permissions.manage",
        permission_name="管理功能权限配置",
        module_code="system",
        page_code="function_permission_config",
        action_permission_codes=(
            "authz.role_permissions.view",
            "authz.role_permissions.update",
        ),
        hidden_in_capability_pack=True,
        assignable_role_codes=(ROLE_SYSTEM_ADMIN,),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.view",
        permission_name="查看用户列表",
        module_code="user",
        page_code="user_management",
        action_permission_codes=(
            "user.users.list",
            "user.users.detail",
            "user.roles.list",
            "user.roles.detail",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.create",
        permission_name="新建用户",
        module_code="user",
        page_code="user_management",
        action_permission_codes=("user.users.create",),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.update",
        permission_name="编辑用户",
        module_code="user",
        page_code="user_management",
        action_permission_codes=("user.users.update",),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.lifecycle",
        permission_name="启用停用用户",
        module_code="user",
        page_code="user_management",
        action_permission_codes=(
            "user.users.enable",
            "user.users.disable",
        ),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.password_reset",
        permission_name="重置用户密码",
        module_code="user",
        page_code="user_management",
        action_permission_codes=("user.users.reset_password",),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.delete",
        permission_name="删除用户",
        module_code="user",
        page_code="user_management",
        action_permission_codes=("user.users.delete",),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.export",
        permission_name="导出用户列表",
        module_code="user",
        page_code="user_management",
        action_permission_codes=("user.users.export",),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.registration_approval.view",
        permission_name="查看注册申请",
        module_code="user",
        page_code="registration_approval",
        action_permission_codes=("user.registration_requests.list",),
    ),
    FeatureDefinition(
        permission_code="feature.user.registration_approval.approve",
        permission_name="通过注册申请",
        module_code="user",
        page_code="registration_approval",
        action_permission_codes=("user.registration_requests.approve",),
        dependency_permission_codes=("feature.user.registration_approval.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.registration_approval.reject",
        permission_name="驳回注册申请",
        module_code="user",
        page_code="registration_approval",
        action_permission_codes=("user.registration_requests.reject",),
        dependency_permission_codes=("feature.user.registration_approval.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.view",
        permission_name="查看角色管理",
        module_code="user",
        page_code="role_management",
        action_permission_codes=(
            "user.roles.list",
            "user.roles.detail",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.create",
        permission_name="新建角色",
        module_code="user",
        page_code="role_management",
        action_permission_codes=("user.roles.create",),
        dependency_permission_codes=("feature.user.role_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.update",
        permission_name="编辑角色",
        module_code="user",
        page_code="role_management",
        action_permission_codes=("user.roles.update",),
        dependency_permission_codes=("feature.user.role_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.lifecycle",
        permission_name="启用停用角色",
        module_code="user",
        page_code="role_management",
        action_permission_codes=(
            "user.roles.enable",
            "user.roles.disable",
        ),
        dependency_permission_codes=("feature.user.role_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.delete",
        permission_name="删除角色",
        module_code="user",
        page_code="role_management",
        action_permission_codes=("user.roles.delete",),
        dependency_permission_codes=("feature.user.role_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.audit_log.view",
        permission_name="查看操作审计日志",
        module_code="user",
        page_code="audit_log",
        action_permission_codes=("user.audit_logs.list",),
    ),
    FeatureDefinition(
        permission_code="feature.user.account_settings.profile_view",
        permission_name="查看个人资料",
        module_code="user",
        page_code="account_settings",
        action_permission_codes=("user.profile.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.account_settings.password_update",
        permission_name="修改本人密码",
        module_code="user",
        page_code="account_settings",
        action_permission_codes=("user.profile.password.update",),
        dependency_permission_codes=("feature.user.account_settings.profile_view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.account_settings.session_view",
        permission_name="查看当前会话",
        module_code="user",
        page_code="account_settings",
        action_permission_codes=("user.sessions.overview",),
        dependency_permission_codes=("feature.user.account_settings.profile_view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.login_session.login_logs_view",
        permission_name="查看登录日志",
        module_code="user",
        page_code="login_session",
        action_permission_codes=("user.sessions.login_logs.list",),
    ),
    FeatureDefinition(
        permission_code="feature.user.login_session.online_view",
        permission_name="查看在线会话",
        module_code="user",
        page_code="login_session",
        action_permission_codes=("user.sessions.online.list",),
    ),
    FeatureDefinition(
        permission_code="feature.user.login_session.force_offline",
        permission_name="强制下线会话",
        module_code="user",
        page_code="login_session",
        action_permission_codes=(
            "user.sessions.force_offline",
            "user.sessions.force_offline.batch",
        ),
        dependency_permission_codes=("feature.user.login_session.online_view",),
        hidden_in_capability_pack=True,
        assignable_role_codes=(ROLE_SYSTEM_ADMIN,),
    ),
    FeatureDefinition(
        permission_code="feature.product.catalog.read",
        permission_name="查看产品目录",
        module_code="product",
        page_code="product_management",
        action_permission_codes=("product.products.list",),
    ),
    FeatureDefinition(
        permission_code="feature.product.product_management.manage",
        permission_name="维护产品主数据",
        module_code="product",
        page_code="product_management",
        action_permission_codes=(
            "product.products.create",
            "product.products.delete",
            "product.lifecycle.update",
        ),
        dependency_permission_codes=("feature.product.catalog.read",),
    ),
    FeatureDefinition(
        permission_code="feature.product.version_analysis.view",
        permission_name="查看产品版本与影响分析",
        module_code="product",
        page_code="product_version_management",
        action_permission_codes=(
            "product.versions.list",
            "product.versions.compare",
            "product.impact.analysis",
        ),
        dependency_permission_codes=("feature.product.catalog.read",),
    ),
    FeatureDefinition(
        permission_code="feature.product.versions.manage",
        permission_name="管理产品版本",
        module_code="product",
        page_code="product_version_management",
        action_permission_codes=(
            "product.versions.manage",
            "product.rollback",
        ),
        dependency_permission_codes=("feature.product.version_analysis.view",),
    ),
    FeatureDefinition(
        permission_code="feature.product.parameters.view",
        permission_name="查看产品参数",
        module_code="product",
        page_code="product_parameter_query",
        action_permission_codes=(
            "product.parameters.view",
            "product.parameter_history.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.product.parameters.edit",
        permission_name="编辑产品参数",
        module_code="product",
        page_code="product_parameter_management",
        action_permission_codes=("product.parameters.update",),
        dependency_permission_codes=("feature.product.parameters.view",),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.ledger.manage",
        permission_name="维护设备台账",
        module_code="equipment",
        page_code="equipment_ledger",
        action_permission_codes=(
            "equipment.admin_owners.list",
            "equipment.ledger.list",
            "equipment.ledger.create",
            "equipment.ledger.update",
            "equipment.ledger.toggle",
            "equipment.ledger.delete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.items.manage",
        permission_name="维护保养项目",
        module_code="equipment",
        page_code="maintenance_item",
        action_permission_codes=(
            "equipment.items.list",
            "equipment.items.create",
            "equipment.items.update",
            "equipment.items.toggle",
            "equipment.items.delete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.plans.manage",
        permission_name="维护保养计划",
        module_code="equipment",
        page_code="maintenance_plan",
        action_permission_codes=(
            "equipment.plans.list",
            "equipment.plans.create",
            "equipment.plans.update",
            "equipment.plans.toggle",
            "equipment.plans.delete",
            "equipment.plans.generate",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.executions.operate",
        permission_name="执行保养任务",
        module_code="equipment",
        page_code="maintenance_execution",
        action_permission_codes=(
            "equipment.executions.list",
            "equipment.executions.start",
            "equipment.executions.complete",
            "equipment.executions.cancel",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.records.view",
        permission_name="查看保养记录",
        module_code="equipment",
        page_code="maintenance_record",
        action_permission_codes=("equipment.records.list",),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.rules.manage",
        permission_name="管理设备规则",
        module_code="equipment",
        page_code="equipment_rule_parameter",
        action_permission_codes=(
            "equipment.rules.list",
            "equipment.rules.manage",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.runtime_parameters.manage",
        permission_name="管理运行参数",
        module_code="equipment",
        page_code="equipment_rule_parameter",
        action_permission_codes=(
            "equipment.runtime_parameters.list",
            "equipment.runtime_parameters.manage",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_basics.view",
        permission_name="查看工段与工序",
        module_code="craft",
        page_code="process_management",
        action_permission_codes=(
            "craft.stages.list",
            "craft.processes.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_basics.manage",
        permission_name="维护工段与工序",
        module_code="craft",
        page_code="process_management",
        action_permission_codes=(
            "craft.stages.create",
            "craft.stages.update",
            "craft.stages.delete",
            "craft.processes.create",
            "craft.processes.update",
            "craft.processes.delete",
        ),
        dependency_permission_codes=("feature.craft.process_basics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_templates.view",
        permission_name="查看工艺模板与系统母版",
        module_code="craft",
        page_code="production_process_config",
        action_permission_codes=(
            "craft.system_master_template.view",
            "craft.templates.list",
            "craft.templates.detail",
            "craft.templates.impact.analysis",
            "craft.templates.versions.list",
            "craft.templates.versions.compare",
        ),
        dependency_permission_codes=(
            "feature.product.catalog.read",
            "feature.craft.process_basics.view",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_templates.manage",
        permission_name="维护工艺模板与系统母版",
        module_code="craft",
        page_code="production_process_config",
        action_permission_codes=(
            "craft.system_master_template.create",
            "craft.system_master_template.update",
            "craft.templates.create",
            "craft.templates.export",
            "craft.templates.import",
            "craft.templates.publish",
            "craft.templates.rollback",
            "craft.templates.update",
            "craft.templates.delete",
        ),
        dependency_permission_codes=("feature.craft.process_templates.view",),
    ),
    FeatureDefinition(
        permission_code="feature.craft.kanban.view",
        permission_name="查看工艺看板",
        module_code="craft",
        page_code="craft_kanban",
        action_permission_codes=("craft.kanban.process_metrics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.craft.reference_analysis.view",
        permission_name="查看工艺引用分析",
        module_code="craft",
        page_code="craft_reference_analysis",
        action_permission_codes=(
            "craft.stages.list",
            "craft.processes.list",
        ),
        dependency_permission_codes=("feature.craft.process_basics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.first_articles.view",
        permission_name="查看每日首件",
        module_code="quality",
        page_code="first_article_management",
        action_permission_codes=("quality.first_articles.list",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.first_articles.detail",
        permission_name="查看首件详情",
        module_code="quality",
        page_code="first_article_management",
        action_permission_codes=("quality.first_articles.detail",),
        dependency_permission_codes=("feature.quality.first_articles.view",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.first_articles.disposition",
        permission_name="首件处置",
        module_code="quality",
        page_code="first_article_management",
        action_permission_codes=("quality.first_articles.disposition",),
        dependency_permission_codes=("feature.quality.first_articles.detail",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.stats.view",
        permission_name="查看质量数据统计",
        module_code="quality",
        page_code="quality_data_query",
        action_permission_codes=(
            "quality.stats.overview",
            "quality.stats.processes",
            "quality.stats.operators",
            "quality.stats.products",
            "quality.trend",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.quality.scrap_statistics.view",
        permission_name="查看报废统计（品质归口）",
        module_code="quality",
        page_code="quality_scrap_statistics",
        action_permission_codes=(
            "production.scrap_statistics.list",
            "production.scrap_statistics.detail",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.quality.scrap_statistics.export",
        permission_name="导出报废统计（品质归口）",
        module_code="quality",
        page_code="quality_scrap_statistics",
        action_permission_codes=("production.scrap_statistics.export",),
        dependency_permission_codes=("feature.quality.scrap_statistics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.repair_orders.manage",
        permission_name="处理维修订单（品质归口）",
        module_code="quality",
        page_code="quality_repair_orders",
        action_permission_codes=(
            "production.repair_orders.list",
            "production.repair_orders.detail",
            "production.repair_orders.phenomena_summary",
            "production.repair_orders.complete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.quality.repair_orders.export",
        permission_name="导出维修订单（品质归口）",
        module_code="quality",
        page_code="quality_repair_orders",
        action_permission_codes=("production.repair_orders.export",),
        dependency_permission_codes=("feature.quality.repair_orders.manage",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.defect_analysis.view",
        permission_name="查看不良分析",
        module_code="quality",
        page_code="quality_defect_analysis",
        action_permission_codes=("quality.defect_analysis.list",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.defect_analysis.export",
        permission_name="导出不良分析",
        module_code="quality",
        page_code="quality_defect_analysis",
        action_permission_codes=("quality.defect_analysis.export",),
        dependency_permission_codes=("feature.quality.defect_analysis.view",),
    ),
    FeatureDefinition(
        permission_code="feature.production.order_management.manage",
        permission_name="维护生产订单",
        module_code="production",
        page_code="production_order_management",
        action_permission_codes=(
            "production.orders.list",
            "production.orders.create",
            "production.orders.detail",
            "production.orders.detail_all",
            "production.orders.update",
            "production.orders.delete",
            "production.orders.complete",
        ),
        dependency_permission_codes=(
            "feature.product.catalog.read",
            "feature.craft.process_basics.view",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.pipeline_mode.manage",
        permission_name="维护并行生产模式",
        module_code="production",
        page_code="production_order_management",
        action_permission_codes=(
            "production.orders.pipeline_mode.view",
            "production.orders.pipeline_mode.view_all",
            "production.orders.pipeline_mode.update",
        ),
        dependency_permission_codes=("feature.production.order_management.manage",),
    ),
    FeatureDefinition(
        permission_code="feature.production.order_query.execute",
        permission_name="执行首件与报工",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=(
            "production.my_orders.list",
            "production.my_orders.context",
            "production.execution.first_article",
            "production.execution.end_production",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.order_query.proxy",
        permission_name="代理视角查看工单",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=(
            "production.my_orders.proxy",
            "production.my_orders.view_all",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.assist.launch",
        permission_name="发起代班",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=(
            "production.assist_authorizations.create",
            "production.assist_user_options.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.assist.records.view",
        permission_name="查看代班记录",
        module_code="production",
        page_code="production_assist_approval",
        action_permission_codes=(
            "production.assist_authorizations.list",
            "production.assist_authorizations.review",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.data_query.view",
        permission_name="查看生产数据三视图",
        module_code="production",
        page_code="production_data_query",
        action_permission_codes=(
            "production.stats.overview",
            "production.stats.processes",
            "production.stats.operators",
            "production.data.today_realtime",
            "production.data.unfinished_progress",
            "production.data.manual",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.data_export.use",
        permission_name="导出生产手动筛选数据",
        module_code="production",
        page_code="production_data_query",
        action_permission_codes=("production.data.manual.export",),
        dependency_permission_codes=("feature.production.data_query.view",),
    ),
    FeatureDefinition(
        permission_code="feature.production.scrap_statistics.view",
        permission_name="查看报废统计",
        module_code="production",
        page_code="production_scrap_statistics",
        action_permission_codes=("production.scrap_statistics.list",),
    ),
    FeatureDefinition(
        permission_code="feature.production.scrap_export.use",
        permission_name="导出报废统计",
        module_code="production",
        page_code="production_scrap_statistics",
        action_permission_codes=("production.scrap_statistics.export",),
        dependency_permission_codes=("feature.production.scrap_statistics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.production.repair_orders.manage",
        permission_name="处理维修订单",
        module_code="production",
        page_code="production_repair_orders",
        action_permission_codes=(
            "production.repair_orders.list",
            "production.repair_orders.phenomena_summary",
            "production.repair_orders.complete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.repair_orders.export",
        permission_name="导出维修订单",
        module_code="production",
        page_code="production_repair_orders",
        action_permission_codes=("production.repair_orders.export",),
        dependency_permission_codes=("feature.production.repair_orders.manage",),
    ),
    FeatureDefinition(
        permission_code="feature.production.repair_orders.create_manual",
        permission_name="手工送修建单",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=("production.repair_orders.create_manual",),
        dependency_permission_codes=("feature.production.order_query.execute",),
    ),
    FeatureDefinition(
        permission_code="feature.production.pipeline_instances.view",
        permission_name="查看并行实例追踪",
        module_code="production",
        page_code="production_pipeline_instances",
        action_permission_codes=("production.pipeline_instances.list",),
        dependency_permission_codes=("feature.production.order_management.manage",),
    ),
    FeatureDefinition(
        permission_code="feature.message.center.view",
        permission_name="查看消息中心",
        module_code="message",
        page_code="message_center",
        action_permission_codes=(
            "message.messages.list",
            "message.messages.unread_count",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.message.read.manage",
        permission_name="管理消息已读状态",
        module_code="message",
        page_code="message_center",
        action_permission_codes=(
            "message.messages.read",
            "message.messages.read_all",
        ),
        dependency_permission_codes=("feature.message.center.view",),
    ),
    FeatureDefinition(
        permission_code="feature.message.announcement.publish",
        permission_name="发布站内公告",
        module_code="message",
        page_code="message_center",
        action_permission_codes=("message.announcements.publish",),
        dependency_permission_codes=("feature.message.center.view",),
    ),
)


FEATURE_BY_PERMISSION_CODE = {
    item.permission_code: item for item in FEATURE_DEFINITIONS
}
