from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ModuleDefinition:
    module_code: str
    module_name: str


@dataclass(frozen=True, slots=True)
class FeatureDefinition:
    permission_code: str
    permission_name: str
    module_code: str
    page_code: str
    action_permission_codes: tuple[str, ...]
    dependency_permission_codes: tuple[str, ...] = ()


def module_permission_code(module_code: str) -> str:
    return f"module.{module_code}.access"


MODULE_DEFINITIONS: tuple[ModuleDefinition, ...] = (
    ModuleDefinition(module_code="system", module_name="系统管理"),
    ModuleDefinition(module_code="user", module_name="用户管理"),
    ModuleDefinition(module_code="product", module_name="产品管理"),
    ModuleDefinition(module_code="equipment", module_name="设备管理"),
    ModuleDefinition(module_code="craft", module_name="工艺管理"),
    ModuleDefinition(module_code="quality", module_name="质量管理"),
    ModuleDefinition(module_code="production", module_name="生产管理"),
)


MODULE_NAME_BY_CODE = {item.module_code: item.module_name for item in MODULE_DEFINITIONS}


FEATURE_DEFINITIONS: tuple[FeatureDefinition, ...] = (
    FeatureDefinition(
        permission_code="feature.system.permission_catalog.view",
        permission_name="查看权限目录",
        module_code="system",
        page_code="function_permission_config",
        action_permission_codes=(
            "authz.permissions.catalog.view",
            "authz.permissions.me.view",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.system.role_permissions.manage",
        permission_name="管理功能权限配置",
        module_code="system",
        page_code="function_permission_config",
        action_permission_codes=(
            "authz.role_permissions.view",
            "authz.role_permissions.update",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.view",
        permission_name="查看用户与角色信息",
        module_code="user",
        page_code="user_management",
        action_permission_codes=(
            "user.users.list",
            "user.users.detail",
            "user.roles.list",
            "user.roles.detail",
            "user.processes.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.user_management.manage",
        permission_name="维护用户信息",
        module_code="user",
        page_code="user_management",
        action_permission_codes=(
            "user.users.create",
            "user.users.update",
            "user.users.delete",
            "user.users.enable",
            "user.users.disable",
            "user.users.reset_password",
            "user.users.export",
        ),
        dependency_permission_codes=("feature.user.user_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.registration_approval.review",
        permission_name="处理注册审批",
        module_code="user",
        page_code="registration_approval",
        action_permission_codes=(
            "user.registration_requests.list",
            "user.registration_requests.approve",
            "user.registration_requests.reject",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.view",
        permission_name="查看角色管理",
        module_code="user",
        page_code="role_management",
        action_permission_codes=(
            "user.roles.list",
            "user.roles.detail",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.role_management.manage",
        permission_name="维护角色信息",
        module_code="user",
        page_code="role_management",
        action_permission_codes=(
            "user.roles.create",
            "user.roles.update",
            "user.roles.enable",
            "user.roles.disable",
            "user.roles.delete",
        ),
        dependency_permission_codes=("feature.user.role_management.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.audit_log.view",
        permission_name="查看操作审计日志",
        module_code="user",
        page_code="audit_log",
        action_permission_codes=("user.audit_logs.list",),
    ),
    FeatureDefinition(
        permission_code="feature.user.account_settings.view",
        permission_name="查看个人中心",
        module_code="user",
        page_code="account_settings",
        action_permission_codes=(
            "user.profile.view",
            "user.sessions.overview",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.account_settings.manage",
        permission_name="维护账号安全设置",
        module_code="user",
        page_code="account_settings",
        action_permission_codes=("user.profile.password.update",),
        dependency_permission_codes=("feature.user.account_settings.view",),
    ),
    FeatureDefinition(
        permission_code="feature.user.login_session.view",
        permission_name="查看登录日志与在线会话",
        module_code="user",
        page_code="login_session",
        action_permission_codes=(
            "user.sessions.login_logs.list",
            "user.sessions.online.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.user.login_session.manage",
        permission_name="管理在线会话",
        module_code="user",
        page_code="login_session",
        action_permission_codes=(
            "user.sessions.force_offline",
            "user.sessions.force_offline.batch",
        ),
        dependency_permission_codes=("feature.user.login_session.view",),
    ),
    FeatureDefinition(
        permission_code="feature.product.catalog.read",
        permission_name="查看产品目录",
        module_code="product",
        page_code="product_management",
        action_permission_codes=("product.products.list",),
    ),
    FeatureDefinition(
        permission_code="feature.product.product_management.manage",
        permission_name="维护产品主数据",
        module_code="product",
        page_code="product_management",
        action_permission_codes=(
            "product.products.create",
            "product.products.delete",
            "product.lifecycle.update",
            "product.rollback",
        ),
        dependency_permission_codes=("feature.product.catalog.read",),
    ),
    FeatureDefinition(
        permission_code="feature.product.version_analysis.view",
        permission_name="查看产品版本与影响分析",
        module_code="product",
        page_code="product_management",
        action_permission_codes=(
            "product.versions.list",
            "product.versions.compare",
            "product.impact.analysis",
        ),
        dependency_permission_codes=("feature.product.catalog.read",),
    ),
    FeatureDefinition(
        permission_code="feature.product.versions.manage",
        permission_name="管理产品版本",
        module_code="product",
        page_code="product_management",
        action_permission_codes=(
            "product.versions.manage",
        ),
        dependency_permission_codes=("feature.product.version_analysis.view",),
    ),
    FeatureDefinition(
        permission_code="feature.product.parameters.view",
        permission_name="查看产品参数",
        module_code="product",
        page_code="product_parameter_query",
        action_permission_codes=(
            "product.parameters.view",
            "product.parameter_history.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.product.parameters.edit",
        permission_name="编辑产品参数",
        module_code="product",
        page_code="product_parameter_management",
        action_permission_codes=("product.parameters.update",),
        dependency_permission_codes=("feature.product.parameters.view",),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.ledger.manage",
        permission_name="维护设备台账",
        module_code="equipment",
        page_code="equipment_ledger",
        action_permission_codes=(
            "equipment.admin_owners.list",
            "equipment.ledger.list",
            "equipment.ledger.create",
            "equipment.ledger.update",
            "equipment.ledger.toggle",
            "equipment.ledger.delete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.items.manage",
        permission_name="维护保养项目",
        module_code="equipment",
        page_code="maintenance_item",
        action_permission_codes=(
            "equipment.items.list",
            "equipment.items.create",
            "equipment.items.update",
            "equipment.items.toggle",
            "equipment.items.delete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.plans.manage",
        permission_name="维护保养计划",
        module_code="equipment",
        page_code="maintenance_plan",
        action_permission_codes=(
            "equipment.plans.list",
            "equipment.plans.create",
            "equipment.plans.update",
            "equipment.plans.toggle",
            "equipment.plans.delete",
            "equipment.plans.generate",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.executions.operate",
        permission_name="执行保养任务",
        module_code="equipment",
        page_code="maintenance_execution",
        action_permission_codes=(
            "equipment.executions.list",
            "equipment.executions.start",
            "equipment.executions.complete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.equipment.records.view",
        permission_name="查看保养记录",
        module_code="equipment",
        page_code="maintenance_record",
        action_permission_codes=("equipment.records.list",),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_basics.view",
        permission_name="查看工段与工序",
        module_code="craft",
        page_code="process_management",
        action_permission_codes=(
            "craft.stages.list",
            "craft.processes.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_basics.manage",
        permission_name="维护工段与工序",
        module_code="craft",
        page_code="process_management",
        action_permission_codes=(
            "craft.stages.create",
            "craft.stages.update",
            "craft.stages.delete",
            "craft.processes.create",
            "craft.processes.update",
            "craft.processes.delete",
        ),
        dependency_permission_codes=("feature.craft.process_basics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_templates.view",
        permission_name="查看工艺模板与系统母版",
        module_code="craft",
        page_code="production_process_config",
        action_permission_codes=(
            "craft.system_master_template.view",
            "craft.templates.list",
            "craft.templates.detail",
            "craft.templates.impact.analysis",
            "craft.templates.versions.list",
            "craft.templates.versions.compare",
        ),
        dependency_permission_codes=(
            "feature.product.catalog.read",
            "feature.craft.process_basics.view",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.craft.process_templates.manage",
        permission_name="维护工艺模板与系统母版",
        module_code="craft",
        page_code="production_process_config",
        action_permission_codes=(
            "craft.system_master_template.create",
            "craft.system_master_template.update",
            "craft.templates.create",
            "craft.templates.export",
            "craft.templates.import",
            "craft.templates.publish",
            "craft.templates.rollback",
            "craft.templates.update",
            "craft.templates.delete",
        ),
        dependency_permission_codes=("feature.craft.process_templates.view",),
    ),
    FeatureDefinition(
        permission_code="feature.craft.kanban.view",
        permission_name="查看工艺看板",
        module_code="craft",
        page_code="craft_kanban",
        action_permission_codes=("craft.kanban.process_metrics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.first_articles.view",
        permission_name="查看每日首件",
        module_code="quality",
        page_code="first_article_management",
        action_permission_codes=("quality.first_articles.list",),
    ),
    FeatureDefinition(
        permission_code="feature.quality.stats.view",
        permission_name="查看质量数据统计",
        module_code="quality",
        page_code="quality_data_query",
        action_permission_codes=(
            "quality.stats.overview",
            "quality.stats.processes",
            "quality.stats.operators",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.order_management.manage",
        permission_name="维护生产订单",
        module_code="production",
        page_code="production_order_management",
        action_permission_codes=(
            "production.orders.list",
            "production.orders.create",
            "production.orders.detail",
            "production.orders.detail_all",
            "production.orders.update",
            "production.orders.delete",
            "production.orders.complete",
        ),
        dependency_permission_codes=(
            "feature.product.catalog.read",
            "feature.craft.process_basics.view",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.pipeline_mode.manage",
        permission_name="维护并行生产模式",
        module_code="production",
        page_code="production_order_management",
        action_permission_codes=(
            "production.orders.pipeline_mode.view",
            "production.orders.pipeline_mode.view_all",
            "production.orders.pipeline_mode.update",
        ),
        dependency_permission_codes=("feature.production.order_management.manage",),
    ),
    FeatureDefinition(
        permission_code="feature.production.order_query.execute",
        permission_name="执行首件与报工",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=(
            "production.my_orders.list",
            "production.my_orders.context",
            "production.execution.first_article",
            "production.execution.end_production",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.order_query.proxy",
        permission_name="代理视角查看工单",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=(
            "production.my_orders.proxy",
            "production.my_orders.view_all",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.assist.launch",
        permission_name="发起代班",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=(
            "production.assist_authorizations.create",
            "production.assist_user_options.list",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.assist.records.view",
        permission_name="查看代班记录",
        module_code="production",
        page_code="production_assist_approval",
        action_permission_codes=(
            "production.assist_authorizations.list",
            "production.assist_authorizations.review",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.data_query.view",
        permission_name="查看生产数据三视图",
        module_code="production",
        page_code="production_data_query",
        action_permission_codes=(
            "production.stats.overview",
            "production.stats.processes",
            "production.stats.operators",
            "production.data.today_realtime",
            "production.data.unfinished_progress",
            "production.data.manual",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.data_export.use",
        permission_name="导出生产手动筛选数据",
        module_code="production",
        page_code="production_data_query",
        action_permission_codes=("production.data.manual.export",),
        dependency_permission_codes=("feature.production.data_query.view",),
    ),
    FeatureDefinition(
        permission_code="feature.production.scrap_statistics.view",
        permission_name="查看报废统计",
        module_code="production",
        page_code="production_scrap_statistics",
        action_permission_codes=("production.scrap_statistics.list",),
    ),
    FeatureDefinition(
        permission_code="feature.production.scrap_export.use",
        permission_name="导出报废统计",
        module_code="production",
        page_code="production_scrap_statistics",
        action_permission_codes=("production.scrap_statistics.export",),
        dependency_permission_codes=("feature.production.scrap_statistics.view",),
    ),
    FeatureDefinition(
        permission_code="feature.production.repair_orders.manage",
        permission_name="处理维修订单",
        module_code="production",
        page_code="production_repair_orders",
        action_permission_codes=(
            "production.repair_orders.list",
            "production.repair_orders.phenomena_summary",
            "production.repair_orders.complete",
        ),
    ),
    FeatureDefinition(
        permission_code="feature.production.repair_orders.export",
        permission_name="导出维修订单",
        module_code="production",
        page_code="production_repair_orders",
        action_permission_codes=("production.repair_orders.export",),
        dependency_permission_codes=("feature.production.repair_orders.manage",),
    ),
    FeatureDefinition(
        permission_code="feature.production.repair_orders.create_manual",
        permission_name="手工送修建单",
        module_code="production",
        page_code="production_order_query",
        action_permission_codes=("production.repair_orders.create_manual",),
        dependency_permission_codes=("feature.production.order_query.execute",),
    ),
)


FEATURE_BY_PERMISSION_CODE = {item.permission_code: item for item in FEATURE_DEFINITIONS}
