ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_IN_PROGRESS = "in_progress"
ORDER_STATUS_COMPLETED = "completed"

PROCESS_STATUS_PENDING = "pending"
PROCESS_STATUS_IN_PROGRESS = "in_progress"
PROCESS_STATUS_PARTIAL = "partial"
PROCESS_STATUS_COMPLETED = "completed"

SUB_ORDER_STATUS_PENDING = "pending"
SUB_ORDER_STATUS_IN_PROGRESS = "in_progress"
SUB_ORDER_STATUS_DONE = "done"

RECORD_TYPE_FIRST_ARTICLE = "first_article"
RECORD_TYPE_PRODUCTION = "production"

ORDER_STATUS_ALL = {
    ORDER_STATUS_PENDING,
    ORDER_STATUS_IN_PROGRESS,
    ORDER_STATUS_COMPLETED,
}
PROCESS_STATUS_ALL = {
    PROCESS_STATUS_PENDING,
    PROCESS_STATUS_IN_PROGRESS,
    PROCESS_STATUS_PARTIAL,
    PROCESS_STATUS_COMPLETED,
}
SUB_ORDER_STATUS_ALL = {
    SUB_ORDER_STATUS_PENDING,
    SUB_ORDER_STATUS_IN_PROGRESS,
    SUB_ORDER_STATUS_DONE,
}

