PRODUCT_LIFECYCLE_ACTIVE = "active"
PRODUCT_LIFECYCLE_INACTIVE = "inactive"

PRODUCT_LIFECYCLE_OPTIONS = {
    PRODUCT_LIFECYCLE_ACTIVE,
    PRODUCT_LIFECYCLE_INACTIVE,
}

PRODUCT_LIFECYCLE_TRANSITIONS: dict[str, set[str]] = {
    PRODUCT_LIFECYCLE_ACTIVE: {
        PRODUCT_LIFECYCLE_INACTIVE,
    },
    PRODUCT_LIFECYCLE_INACTIVE: {
        PRODUCT_LIFECYCLE_ACTIVE,
    },
}

PRODUCT_LIFECYCLE_DRAFT = "draft"
PRODUCT_LIFECYCLE_EFFECTIVE = "effective"
PRODUCT_LIFECYCLE_OBSOLETE = "obsolete"

PRODUCT_REVISION_LIFECYCLE_OPTIONS = {
    PRODUCT_LIFECYCLE_DRAFT,
    PRODUCT_LIFECYCLE_EFFECTIVE,
    PRODUCT_LIFECYCLE_OBSOLETE,
    PRODUCT_LIFECYCLE_INACTIVE,
}

PRODUCT_REVISION_LIFECYCLE_TRANSITIONS: dict[str, set[str]] = {
    PRODUCT_LIFECYCLE_DRAFT: {
        PRODUCT_LIFECYCLE_EFFECTIVE,
        PRODUCT_LIFECYCLE_INACTIVE,
    },
    PRODUCT_LIFECYCLE_EFFECTIVE: {
        PRODUCT_LIFECYCLE_OBSOLETE,
        PRODUCT_LIFECYCLE_INACTIVE,
    },
    PRODUCT_LIFECYCLE_OBSOLETE: set(),
    PRODUCT_LIFECYCLE_INACTIVE: {
        PRODUCT_LIFECYCLE_EFFECTIVE,
        PRODUCT_LIFECYCLE_OBSOLETE,
    },
}
