PRODUCT_LIFECYCLE_DRAFT = "draft"
PRODUCT_LIFECYCLE_PENDING_REVIEW = "pending_review"
PRODUCT_LIFECYCLE_EFFECTIVE = "effective"
PRODUCT_LIFECYCLE_INACTIVE = "inactive"

PRODUCT_LIFECYCLE_OPTIONS = {
    PRODUCT_LIFECYCLE_DRAFT,
    PRODUCT_LIFECYCLE_PENDING_REVIEW,
    PRODUCT_LIFECYCLE_EFFECTIVE,
    PRODUCT_LIFECYCLE_INACTIVE,
}

# Allowed status transitions for product lifecycle management.
PRODUCT_LIFECYCLE_TRANSITIONS: dict[str, set[str]] = {
    PRODUCT_LIFECYCLE_DRAFT: {
        PRODUCT_LIFECYCLE_PENDING_REVIEW,
        PRODUCT_LIFECYCLE_EFFECTIVE,
    },
    PRODUCT_LIFECYCLE_PENDING_REVIEW: {
        PRODUCT_LIFECYCLE_DRAFT,
        PRODUCT_LIFECYCLE_EFFECTIVE,
    },
    PRODUCT_LIFECYCLE_EFFECTIVE: {
        PRODUCT_LIFECYCLE_INACTIVE,
    },
    PRODUCT_LIFECYCLE_INACTIVE: {
        PRODUCT_LIFECYCLE_EFFECTIVE,
    },
}

